apiVersion: v1
data:
  WALLET_PASSWORD: longpass
  WALLET_USERNAME: luke
  INPUT_FILE_PATH: /volume/tick.log
  OUTPUT_FILE_PATH: /volume/tick.log
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    service: luke-web-envfile
  name: luke-web-envfile
