apiVersion: v1
kind: Service
metadata:
  labels:
    service: luke-web
  name: luke-web
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8000
  selector:
    service: luke-web
status:
  loadBalancer: {}
