apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: luke-web-claim0
  name: luke-web-volume
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
